name: docker

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      type:
        description: 'Type'
        required: true
        default: javascript

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
        options: >-
          -v /tmp/.buildx-cache:/var/lib/registry

    name: Docker...
    steps:
      - uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Build and push to local registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          tags: localhost:5000/test:latest
          cache-from: type=registry,ref=localhost:5000/test:buildcache
          cache-to: type=registry,ref=localhost:5000/test:buildcache,mode=max
          push: true

      - name: Inspect
        run: |
          ls -la /tmp/.buildx-cache
          image=localhost:5000/test
          tag=latest
          name=test
          inspect=$(docker buildx imagetools inspect $image:$tag)
          platforms=linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          echo $inspect

          mkdir -p /tmp/zip
          IFS=',' read -ra ARR <<< "$platforms"
          for plat in "${ARR[@]}"; do
            p=$(echo "${plat//\//}")
            p=$(echo "${p//linux/}")
            perImage=$(echo $inspect | grep -B 2 $plat | grep Name: | awk '{print $2}')
            folder=/tmp/zip/$name-$p
            mkdir -p $folder
            docker create --name $name-$p $perImage && docker cp $name-$p:/log /tmp/zip/$name-$p/log && docker rm $name-$p
            cd $folder; zip -r /tmp/zip/$name.$p.zip ./; cd -
            ls -la $folder
          done

          docker buildx prune -f --filter until=24h
