name: docker

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      type:
        description: 'Type'
        required: true
        default: javascript

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
        options: >-
          -v /tmp/.buildx-cache:/var/lib/registry

    name: Docker...
    steps:
      - uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Build and push to local registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          tags: localhost:5000/test:latest
          cache-from: type=registry,ref=localhost:5000/test:buildcache
          cache-to: type=registry,ref=localhost:5000/test:buildcache,mode=max
          push: true

      - name: Inspect
        run: |
          docker buildx imagetools inspect localhost:5000/test:latest
          docker buildx prune -f --filter until=24h
