name: GH-context

on:
  create: 
    branches:
      - release/**
    tags:
      - v*
  push:
    branches:
      - main
      - hotfix/**
    tags:
      - v*
    paths-ignore:
      - 'p1/**'
      - '.github/workflows/p1.yml'
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches:
      - main
      - hotfix/**
    paths-ignore:
      - 'p1/**'
      - '.github/workflows/p1.yml'
  workflow_dispatch:

jobs:
  context:
    runs-on: ubuntu-latest
    name: Project context
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: false
          git_push_gpgsign: false

      - name: List keys
        run: gpg -K

      - id: context
        uses: zero88/gh-project-context@main
        with:
          changelog: true
          nextVerMode: PATCH
          token: ${{ secrets.GITHUB_TOKEN }}
