name: GH-context

on:
  create: 
    branches:
      - release/**
    tags:
      - v*
  push:
    branches:
      - main
      - hotfix/**
    tags:
      - v*
    paths-ignore:
      - 'p1/**'
      - '.github/workflows/p1.yml'
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches:
      - main
      - hotfix/**
    paths-ignore:
      - 'p1/**'
      - '.github/workflows/p1.yml'
  workflow_dispatch:

jobs:
  context:
    runs-on: ubuntu-latest
    name: Project context
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - id: context
        uses: zero88/gh-project-context@main
        with:
          changelog: true
          nextVerMode: PATCH
          token: ${{ secrets.GITHUB_TOKEN }}
