name: First run

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches:
      - 'main'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.OSS_GITHUB_TOKEN }}
      - id: foo
        uses: zero88/gh-project-context@main
        with:
          dry: false
