name: GH-context

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - 'p1/**'
      - '.github/workflows/p1.yml'
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches:
      - 'main'
    paths-ignore:
      - 'p1/**'
      - '.github/workflows/p1.yml'
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.OSS_GITHUB_TOKEN }}
      - id: foo
        uses: zero88/gh-project-context@main
        with:
          dry: false
