name: First run

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      dry:
        description: 'dryRun'
        required: true

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: dryRun
        run: |
          [[ -z "${{ github.event.inputs.dry }}" ]] && dry=false || dry="${{ github.event.inputs.dry }}"
          echo ::set-output name=dry::$dry
      - id: foo
        uses: zero88/gh-project-context@main
        with:
          dry: ${{ steps.dryRun.outputs.dry }}
          patterns: |
            gradle.properties
            package.json
            pyproject.toml
            version.txt
            version.yml
