name: First run

on: 
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      type:
        description: 'Type'
        required: true
        default: javascript


jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - id: projectType
      run: |
        [[ -z "${{ github.event.inputs.type }}" ]] && pt="python-pipenv" || pt="${{ github.event.inputs.type }}"
        echo ::set-output name=pt::$pt
    - id: foo
      uses: zero88/gh-project-context@main
      env: 
        GITHUB_CONTEXT: ${{ toJson(github) }}
      with:
        projectType: ${{ steps.projectType.outputs.pt }}
