name: GH-context

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - 'p1/**'
      - '.github/workflows/p1.yml'
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches:
      - 'main'
    paths-ignore:
      - 'p1/**'
      - '.github/workflows/p1.yml'
  workflow_dispatch:

jobs:
  context:
    runs-on: ubuntu-latest
    name: Alo
    steps:
      - uses: actions/checkout@v2
      
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - id: foo
        uses: zero88/gh-project-context@main
        with:
          dry: false
